# Macro file for example B1
# 
# To be run preferably in batch, without graphics:
# % exampleB1 run2.mac
#
#/run/numberOfWorkers 4
/run/initialize
#
/control/verbose 0
/run/verbose 0
#
# gamma 6 MeV to the direction (0.,0.,1.)
# 10000 events
#
#/gun/particle gamma
#/gun/energy 6 MeV
#
#/run/printProgress 100
#/run/beamOn 1000
# 
# proton 210 MeV to the direction (0.,0.,1.)
# 1000 events
#
/gun/particle ion
/gun/ion 6 12 6
/gun/energy 432 MeV
/run/beamOn 100000000
